name: Build and Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: zip -r build-artifacts.zip dist/
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build-artifacts.zip
          body: "Release of version ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
